services:
  - type: web
    name: feedme-order-controller-backend
    env: node
    rootDir: se-take-home-assignment/backend
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /health
